# AOC 2019

In [239]:
import pandas as pd
import numpy as np
import aocd
import math
import collections

## Day 1

In [240]:
d1 = [int(x) for x in aocd.get_data(day=1,year=2019).split()]

In [241]:
df1 = pd.DataFrame(d1)

In [242]:
a11 = np.sum(df1[0] // 3 - 2)

In [243]:
i = 0
while np.sum(df1[i]) > 0:
    i += 1
    df1[i] = (df1[i - 1] // 3 - 2).clip(0)
    next

a12 = np.sum(np.sum(df1.iloc[:,1:]))


In [244]:
print(a11,a12)

3471229 5203967


## Day 2

In [245]:
d2 = [int(x) for x in aocd.get_data(day=2,year=2019).split(',')]

In [246]:

def intcode(data,p1=12,p2=2):
    out = data[:]
    out[1] = p1
    out[2] = p2

    oploc = 0
    opcode = out[oploc]

    while opcode != 99:
        if opcode == 1:
            out[out[oploc + 3]] = out[out[oploc + 1]] + out[out[oploc + 2]]
            oploc += 4
        elif opcode == 2:
            out[out[oploc + 3]] = out[out[oploc + 1]] * out[out[oploc + 2]]
            oploc += 4
        elif opcode == 3:
            out[out[oploc + 1]] = out[out[oploc + 1]] * out[out[oploc + 2]]
            oploc += 4
        opcode = out[oploc]
    return out[0]

In [247]:
a21 = intcode(d2)

In [248]:
def intcode_test(test_value=19690720,nrange=100,vrange=100):
    for n in range(nrange):
        for v in range(vrange):
            if test_value == intcode(d2,n,v):
                return(100 * n + v)

In [249]:
a22 = intcode_test()

In [250]:
print(a21,a22)

4138658 7264


## Day 3

In [251]:
d3 = aocd.get_data(day=3,year=2019)

In [252]:
wires = [[[0,0]],[[0,0]]]

for i, wire in enumerate(d3.split()):
    path = wire.split(',')
    for e in path:
        start = wires[i][-1]
        for step in range(int(e[1:])):
            if e[0] == 'R':
                wires[i].append([start[0],start[1]+(1+step)])
            elif e[0] == 'L':
                wires[i].append([start[0],start[1]-(1+step)])
            elif e[0] == 'U':
                wires[i].append([start[0]+(1+step),start[1]])
            elif e[0] == 'D':
                wires[i].append([start[0]-(1+step),start[1]])

In [253]:
w0 = pd.DataFrame(wires[0],columns=['x','y'])
w1 = pd.DataFrame(wires[1],columns=['x','y'])

In [254]:
common = pd.merge(w0.reset_index(),w1.reset_index(), on=('x','y'),how='inner')[1:]

In [255]:
print(np.min(abs(common.x) + abs(common.y)))
print(np.min(common.index_x+common.index_y))

2050
21666


## Day 4

In [256]:
d4 = aocd.get_data(day=4,year=2019)

In [257]:
d4

'134564-585159'

In [258]:
cnt = 0
pwds = []
for pwd in range(*[int(x) for x in d4.split('-')]):
    # cnt += 1
    pwdstr = str(pwd)
    if pwdstr[0] > pwdstr[1]:
        continue
    elif pwdstr[1] > pwdstr[2]:
        continue
    elif pwdstr[2] > pwdstr[3]:
        continue
    elif pwdstr[3] > pwdstr[4]:
        continue
    elif pwdstr[4] > pwdstr[5]:
        continue
    elif max(collections.Counter(pwdstr).values()) < 2:
        continue
    else:
        pwds.append(pwdstr)

# PART 1
print(len(pwds))

# PART 2
pwds2 = []
for pwd in pwds:
    if 2 not in collections.Counter(pwd).values():
        continue
    else:
        pwds2.append(pwd)

print(len(pwds2))



1929
1306


## Day 5

In [260]:
d5 = aocd.get_data(day=5,year=2019)

## Day 16

In [2]:
d16 = aocd.get_data(day=16, year=2019)

In [34]:
# part 1
pattern = [0,1,0,-1]
start = np.array([int(e) for e in d16])
out = start.copy()
for _ in range(100):
    for i in range(len(start)):
        pattern_app = np.resize(np.roll(np.repeat(pattern,i+1),-1),len(start))
        out[i] = abs(np.sum(np.multiply(pattern_app,start))) % 10
    start = out.copy()

print(out[:8])

[1 9 2 3 9 4 6 8]


In [13]:
start = np.resize(start,len(start)*10000)

In [39]:
# Repeate 10k times and reverse array after cutoff point
start = np.array([int(e) for e in d16])
shalf = np.resize(start,len(start)*10000)[int(d16[:7]):]

out = shalf[::-1].copy()
for _ in range(100):
    out = np.cumsum(out) % 10
print(out[:-9:-1])

[9 6 9 6 6 2 2 1]


## Day 24

In [236]:
# d24 = [int(i) for x in  aocd.get_data(day=24,year=2019).replace('.','0').replace('#','1').split() for i in list(x) ]
d24 = aocd.get_data(day=24,year=2019)

In [237]:
str24 = d24.replace('.','0').replace('#','1').replace('\n','') 

'0010101011110000101011100'

In [238]:
a24 = np.array([int(x) for x in list(d24)#.reshape(5,5)
np.where(a24 == 1)

(array([ 2,  4,  6,  8,  9, 10, 11, 16, 18, 20, 21, 22]),)

In [181]:
# a24 = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0])

np.sum(np.power(2, np.where(a24==1)))

7671636

In [188]:
array_list = [[a24]]

In [193]:
a24.indices

AttributeError: 'numpy.ndarray' object has no attribute 'indices'

In [234]:
def bug_cycle(input_string):
    tops = [x for x in range(5)]
    bottoms = [x + 20 for x in range(5)]
    lefts = [x * 5 for x in range(5)]
    rights = [x * 5 + 4 for x in range(5)]
    output_list = []
    for i, e in enumerate(list(input_string)):
        check = 0
        if i in tops:
            check += 0 
        else:
            check += int(input_string[i-5])

        if i in bottoms:
            check += 0 
        else:
            check += int(input_string[i+5])

        if i in lefts:
            check += 0 
        else:
            check += int(input_string[i-1])

        if i in rights:
            check += 0 
        else:
            check += int(input_string[i+1])
        
        if int(e) * check == 1 or (e == '0' and check in (1,2)):
            output_list.append('1')
        else:
            output_list.append('0')

        output_string = ''.join(output_list)

    return(output_string)

In [235]:
# print(a24.reshape(5,5))
# print(''.join([str(int(x)) for x in bug_cycle(a24)]))

bug_cycle(''.join([str(i) for i in d24]))
# a24
# a24 in array_list
# for i, e in enumerate(a24):
#     print(i,e)

'0100111010101110000110110'