# Advent of Code

In [1]:
import pandas as pd
import numpy as np
import aocd  # https://github.com/wimglenn/advent-of-code-data
import collections
import itertools
import re

## Day 1

In [2]:
d1 = aocd.get_data(day=1)

In [4]:
def aoc11(data):
    s1 = set(int(x) for x in data.split('\n'))
    s2 = set(2020 - int(x) for x in data.split('\n'))
    a1 = np.prod(list(s1.intersection(s2)))
    return a1

In [6]:
def aoc12(data):
    s1 = set(int(x) for x in data.split('\n'))
    s2 = set(2020 - int(x) for x in data.split('\n'))
    a2 = np.prod(list(set(a for a in s1 for b in s1 if a+b in s2)))
    return a2

In [5]:
%timeit aoc11(d1)

108 µs ± 276 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
%timeit aoc12(d1)

3.11 ms ± 29.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
s1 = set(int(x) for x in d1.split('\n'))
s2 = set(2020 - int(x) for x in d1.split('\n'))

In [5]:
a1 = np.prod(list(s1.intersection(s2)))

In [35]:
aocd.submit(a1, part='a', day=1, year=2020)

You don't seem to be solving the right level.  Did you already complete it? [Return to Day 1]


<Response [200]>

In [6]:
a2 = np.prod(list(set(a for a in s1 for b in s1 if a+b in s2)))

In [46]:
aocd.submit(a2, part='b', day=1, year=2020)

That's the right answer!  You are one gold star closer to saving your vacation.You have completed Day 1! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

## Day 2

In [8]:
d2 = aocd.get_data(day=2)

In [22]:
pswd = d2.split('\n')

In [26]:
t = 0
for e in pswd:
    p_list = e.split()
    low = int(p_list[0].split('-')[0])
    high = int(p_list[0].split('-')[1])
    ltr = p_list[1][0]
    pwd = p_list[2]
    if pwd.count(ltr) >= low and pwd.count(ltr) <= high:
        t +=1

t


458

In [28]:
t = 0
for e in pswd:
    p_list = e.split()
    low = int(p_list[0].split('-')[0])
    high = int(p_list[0].split('-')[1])
    ltr = p_list[1][0]
    pwd = p_list[2]
    if (pwd[low-1] == ltr and pwd[high-1] != ltr) or (pwd[low-1] != ltr and pwd[high-1] == ltr):
        t +=1

t

342

## Day 3

In [2]:
d3 = aocd.get_data(day=3)

In [33]:
def slope(var):
    out = 0
    x = var // 10
    y = var % 10
    for i,e in enumerate(d3.split()[::y]):
        if i == 0:
            next
        if e[(i*x) % len(e)]=='#':
            out += 1 
    return out

#part 1
print(slope(31))

#part 2
p=1
for s in [11,31,51,71,12]:
    p *= slope(s)
print(p)


211
3584591857


## Day 4

In [36]:
d4 = aocd.get_data(day=4, year=2020)

In [41]:
passports = d4.split('\n\n')

In [49]:
#Part 1
d4 = aocd.get_data(day=4, year=2020)
passports = d4.split('\n\n')
valdict = {'byr':1,'eyr':1,'pid':1,'hgt':1,'iyr':1, 'ecl':1, 'hcl':1,'cid':0}
valid = 0
for passport in passports:
    if sum([valdict.get(p.split(':')[0]) for p in passport.split()]) == 7:
        valid += 1
print(valid)

200


In [86]:
def passport_check(byr='0', eyr='0',pid='0',hgt='0',iyr='0', ecl='0', hcl='0',cid=None):
    if int(byr) < 1920 or int(byr) >2002:
        return 0
    if int(iyr) < 2010 or int(iyr) >2020:
        return 0
    if int(eyr) < 2020 or int(eyr) >2030:
        return 0

    if hgt[-2:]=='in':
        if int(hgt[:-2]) < 59 or int(hgt[:-2]) > 76:
            return 0
    elif hgt[-2:]=='cm':
        if int(hgt[:-2]) < 150 or int(hgt[:-2]) > 193:
            return 0
    else:
        return 0

    if not(re.match(r'^#[a-f0-9]{6,6}$',hcl)):
        return 0

    if ecl not in ('amb', 'blu', 'brn', 'gry', 'grn', 'hzl', 'oth'):
        return 0

    if not(re.match(r'^[0-9]{9,9}$',pid)):
        return 0

    return 1
    

In [87]:
valid = 0
for passport in passports:
    valid += passport_check(**{p.split(':')[0] : p.split(':')[1] for p in passport.split()})
print(valid)

116


In [155]:
passports = [p.split() for p in d4.split('\n\n')]
passports_dict = []
for p in passports:
    passports_dict.append(dict(e.split(':') for e in p))

In [158]:
df = pd.DataFrame(passports_dict)

In [159]:
df.dropna(subset=["iyr", "ecl", "hgt", "pid", "byr", "hcl", "eyr"]).shape[0]

200

In [172]:
# pd.to_numeric(df.hgt.str[:-2], errors='coerce') > 1
df['byr'] = pd.to_numeric(df.byr,errors='coerce')
df['eyr'] = pd.to_numeric(df.eyr,errors='coerce')
df['iyr'] = pd.to_numeric(df.iyr,errors='coerce')
df['hgtn'] = pd.to_numeric(df.hgt.str[:-2],errors='coerce')
df['hgtl'] = df.hgt.str[-2:]

In [186]:
df[   (df.byr.between(1920, 2002))
    & (df.iyr.between(2010, 2020))
    & (df.eyr.between(2020, 2030))
    & (df.ecl.isin(["amb", "blu", "brn", "gry", "grn", "hzl", "oth"]))
    & (df.pid.str.match(r'^[0-9]{9}$'))
    & (df.hcl.str.match(r'^#[a-f0-9]{
        6}$'))
    & ( ((df.hgtl == 'cm') & (df.hgtn.between(150,193))) |
        ((df.hgtl == 'in') & (df.hgtn.between( 59, 76))) )
    ]

byr     eyr        pid    hgt     iyr  ecl      hcl  cid   hgtn hgtl
0    1937.0  2030.0  154364481  158cm  2015.0  brn  #c0946f  155  158.0   cm
2    1953.0  2023.0  282499883  181cm  2011.0  brn  #341e13  NaN  181.0   cm
4    1966.0  2020.0  900693718  153cm  2014.0  gry  #866857  NaN  153.0   cm
5    1939.0  2020.0  900852891  162cm  2020.0  oth  #b6652a  NaN  162.0   cm
7    1938.0  2020.0  136823471  180cm  2011.0  gry  #c0946f  146  180.0   cm
..      ...     ...        ...    ...     ...  ...      ...  ...    ...  ...
252  1979.0  2028.0  874418818  166cm  2014.0  brn  #5311ca  202  166.0   cm
253  1987.0  2027.0  986096798  161cm  2019.0  grn  #6b5442   74  161.0   cm
255  1965.0  2023.0  214991920  185cm  2010.0  brn  #866857  236  185.0   cm
256  1948.0  2025.0  885169578  175cm  2010.0  hzl  #18171d  NaN  175.0   cm
262  1979.0  2023.0  945115479  188cm  2014.0  blu  #b6652a  NaN  188.0   cm

[116 rows x 10 columns]

## Day 5


In [187]:
d5 = aocd.get_data(day=5,year=2020)

In [202]:
d5 = d5.replace('B','1')
d5 = d5.replace('F','0')
d5 = d5.replace('R','1')
d5 = d5.replace('L','0')

seat_val = []
for seat in d5.split():
    seat_val.append(int(seat[:7],2) * 8 + int(seat[7:],2))


933

In [195]:
max(seat_val)

1865

In [206]:
for i in range(min(seat_val),max(seat_val)):
    if i not in seat_val:
        print(i)


711


## Day 6

In [211]:
d6 = aocd.get_data(day=6,year=2020)

In [235]:
a = 0
for q in d6.split('\n\n'):
    a += len(collections.Counter(q.replace('\n','')))

print(a)

6310


In [234]:
a=0
for q in d6.split('\n\n'):
    g_dict = collections.Counter(q.replace('\n',''))
    g_size = len(q.split())
    for v in g_dict.values():
        if v == g_size:
            a += 1
print(a)

3193


## Day 7

In [238]:
d7 = aocd.get_data(day=7,year=2020)

In [242]:
all_bags = d7.split('\n')

In [312]:
# parse data into dict of dicts
all_bag_list = {}
for rule in all_bags:
    bag_list = rule.split('bags contain')
    container = bag_list[0].strip()
    contents = bag_list[1].split(',')
    nums = []
    colors = []
    for detail in contents:
        nums.append(int(detail.replace('no other ','0 ').split()[0].strip()))
        for color in re.split(r"\d ",detail)[1:]:
            colors.append(color.split(' bag')[0])
    all_bag_list[container] = dict(zip(colors,nums))


In [314]:

# part 1
out = ['shiny gold']

restart = 1

while restart == 1:
    restart = 0
    # look at all parent / child relationships
    for parent, children in all_bag_list.items():

        for child, num in children.items():
            # test if each child is in the test set
            # if the parent is already included skip, otherwise add parent and rerun from the beginning
            if child in out and parent not in out:
                out.append(parent)
                restart = 1

# find length of unique set and remove seed value
print(len(set(out))-1)


161


In [351]:
# PART 2

new = [['shiny gold',1]]
cnt = 0

while len(new) != 0:
    add_item, mult = new.pop()
    for k,v in all_bag_list.get(add_item).items():
        new.append([k,v * mult])
        cnt += v * mult
print(cnt)

30899


## Day 8

In [352]:
d8 = aocd.get_data(day=8, year=2020)

In [390]:
inst = [(x.split()[0],int(x.split()[1])) for x in d8.split('\n')]

In [364]:
accumlator = 0
locations = set()
location = 0

while location not in locations or location >= len(inst):
    locations.add(location)
    if inst[location][0] == 'acc':
        accumlator += inst[location][1]
        location += 1
    elif inst[location][0] == 'jmp':
        location += inst[location][1]
    elif inst[location][0] == 'nop':
        location += 1

print(accumlator)

1753


In [394]:
for i,e in enumerate(inst):
    accumlator = 0
    locations = set()
    location = 0

    while location not in locations and location < len(inst):
        locations.add(location)
        if inst[location][0] == 'acc':
            accumlator += inst[location][1]
            location += 1
        elif inst[location][0] == 'nop' or (inst[location][0] == 'jmp' and location == i):
            location += 1
        elif inst[location][0] == 'jmp' or (inst[location][0] == 'nop' and location == i):
            location += inst[location][1]
    
    if location >= len(inst):
        print(location, accumlator)
        # print(location, accumlator)


641 733



## Day 9

In [395]:
d9 = aocd.get_data(day=9, year=2020)

In [424]:
base = [int(x) for x in d9.split()]
list_length = 25

for i in range(len(base) - list_length):
    sum_set = set(sum(x) for x in itertools.combinations(base[i:i+list_length],2))
    # print(i, sum_set, base[i + list_length])
    if base[i + list_length] not in sum_set:
        test_num = base[i + list_length]
        break
print(test_num)


25918798


In [435]:
for list_length in range(2,len(base)):
    out = 0
    for i in range(len(base) - list_length):
        test_list = base[i:i+list_length]
        if sum(test_list) == test_num:
            out = min(test_list) + max(test_list)
            break
    if out != 0:
        break

print(out)

408 17
3340942


## Day 10

In [436]:
d10 = aocd.get_data(day=10,year=2020)

In [456]:
list10 = [int(x) for x in d10.split()]

In [457]:
list10.sort()


In [451]:
ones = 0
threes = 0 
if list10[0] == 1:
    ones += 1
elif list10[0] == 3:
    threes += 1


for i in range(len(list10)-1):
    if list10[i+1] - list10[i] == 1:
        ones += 1
    elif list10[i+1] - list10[i] == 3:
        threes += 1

print(ones*(threes+1))
    

2812


In [458]:
list10.append(0)


In [459]:
list10.sort()

In [463]:
options = []
for e in list10:
    option = 0
    if e+1 in list10:
        option += 1
    if e+2 in list10:
        option += 1
    if e+3 in list10:
        option += 1
    options.append(option)


In [476]:
test_dict = {0:1}
test_dict[1] = test_dict.get(1,0) + test_dict.get(0,0)

test_dict

{0: 1, 1: 1}

In [478]:
d10 = aocd.get_data(day=10,year=2020)
list10 = [0] + [int(x) for x in d10.split()]
list10.sort()

path_dict = {0:1}
for e in list10:
    path_dict[e] = path_dict.get(e,0) + path_dict.get(e-1,0)
    path_dict[e] = path_dict.get(e,0) + path_dict.get(e-2,0)
    path_dict[e] = path_dict.get(e,0) + path_dict.get(e-3,0)
        

path_dict.get(max(list10))

386869246296064

## Day 11

In [483]:
d11 = aocd.get_data(day=11, year=2020)

In [511]:
seats = d11.split()

In [677]:
def seat_fill(layout, view_check=False, occupied_min=4):
    output = layout[:]
    directions = [[-1,-1],[-1,0],[-1,1]
                 ,[ 0,-1]       ,[ 0,1]
                 ,[ 1,-1],[ 1,0],[ 1,1]]

    for ir, row in enumerate(layout):

        for ic, seat in enumerate(list(row)):

            occupied = 0

            if seat == '.':
                next
            
            for d in directions:
                mult = 1

                while (ir + (d[0] * mult)) >= 0 and (ir + (d[0] * mult)) <= (len(layout) - 1) \
                  and (ic + (d[1] * mult)) >= 0 and (ic + (d[1] * mult)) <= (len(row)   - 1):

                    adj_seat_val = layout[ir + (d[0] * mult)][ic + (d[1] * mult)]

                    if adj_seat_val == '.':
                        mult += 1
                        if not(view_check):
                            mult = 1000
                        continue
                    elif adj_seat_val == '#':
                        occupied +=1
                        mult = 1000
                        continue
                        # break
                    else:
                        mult = 1000
                        continue
            
            if seat == 'L' and occupied == 0:
                outlist = list(output[ir])
                outlist[ic] = '#'
                output[ir] = ''.join(outlist)
            elif seat == '#' and occupied >=occupied_min:
                outlist = list(output[ir])
                outlist[ic] = 'L'
                output[ir] = ''.join(outlist)
            
    return(output)



In [678]:
prev = seat_fill(seats)
complete = False
cnt = 0
while not(complete):
    cnt += 1
    cur = seat_fill(prev)
    if cur == prev:
        complete = True
    else:
        prev = cur
print(sum([r.count('#') for r in cur]))

2261


In [679]:
prev = seat_fill(seats,view_check=True,occupied_min=5)
complete = False
cnt = 0
while not(complete):
    cnt += 1
    cur = seat_fill(prev,view_check=True,occupied_min=5)
    if cur == prev:
        complete = True
    else:
        prev = cur
print(sum([r.count('#') for r in cur]))

2039


## Day 12

In [680]:
d12 = aocd.get_data(day=12,year=2020)

In [687]:
t12 = [(x[0],int(x[1:])) for x in d12.split()]

In [704]:
x = 0
y = 0
face = 'E'
for t in t12:
    direction = t[0]
    distance = t[1]
    directions = ['N','E','S','W']

    if direction == 'N':
        y += distance
    elif direction == 'S':
        y -= distance
    elif direction == 'E':
        x += distance
    elif direction == 'W':
        x -= distance
    elif direction == 'R':
        face = directions[int((directions.index(face) + (distance / 90) ) % 4)]
    elif direction == 'L':
        face = directions[int((directions.index(face) - (distance / 90) ) % 4)]
    elif direction == 'F':
        if face == 'N':
            y += distance
        elif face == 'S':
            y -= distance
        elif face == 'E':
            x += distance
        elif face == 'W':
            x -= distance
print(abs(x) + abs(y))

1221


In [710]:
x = 0
y = 0
w = [10,1]
for t in t12:
    direction = t[0]
    distance = t[1]
    directions = [[w[0],w[1]],[w[1],-w[0]],[-w[0],-w[1]],[-w[1],w[0]]]

    if direction == 'N':
        w[1] += distance
    elif direction == 'S':
        w[1] -= distance
    elif direction == 'E':
        w[0] += distance
    elif direction == 'W':
        w[0] -= distance
    elif direction == 'R':
        w = directions[int((directions.index(w) + (distance / 90) ) % 4)]
    elif direction == 'L':
        w = directions[int((directions.index(w) - (distance / 90) ) % 4)]
    elif direction == 'F':
        x += distance * w[0]
        y += distance * w[1]
    # print(x,y,t,w)
print(abs(x) + abs(y))

59435


## Day 13

In [711]:
d13 = aocd.get_data(day=13,year=2020)

In [738]:
bus_times = []
wait_times = []
start = int(d13.split()[0])
for b in d13.split()[1].split(','):
    if b != 'x':
        bus_times.append(int(b))
        wait_times.append(int(b) - start % int(b))

print(min(wait_times) * bus_times[wait_times.index(min(wait_times))])


296


In [839]:
bt = d13.split()[1].split(',')

out = 0
inc = int(bt[0])

for i,e in enumerate(bt[1:]):
    if e == 'x':
        continue
    else:
        mod = int(e)
        j = 0
        
        while (mod - (out + j*inc) % mod) % mod != (i+1) % mod:
            j+=1
        out += j*inc
        inc *= mod
print(out)

535296695251210


## Day 14

In [780]:
d14 = aocd.get_data(day=14, year=2020)

In [820]:
program = d14.split('\n')
out = {}

for line in program:
    if line.split()[0] == 'mask':
        mask = list(line.split()[2])
    else:
        loc = int(line.split('[')[1].split(']')[0])
        val = list(bin(int(line.split()[2])))[2:]
        out_list = mask[:]
        for i,e in enumerate(out_list[::-1]):
            if i < len(val) and e =='X':
                out_list[-1-i] = val[-1-i]
                # print(out_list)
            elif e == 'X':
                out_list[-1-i] = '0'
        out_val = int(''.join(out_list),2)
        out[loc] = out_val

sum(out.values())

13496669152158

In [837]:
# read in data and split by line
program = d14.split('\n')

# set up out dict
out = {}

for line in program:
    if line.split()[0] == 'mask':
        # parse mask line to list
        mask = list(line.split()[2])
    
    else:
        # convert location to binary list and drop '0b' marker
        loc = list(bin(int(line.split('[')[1].split(']')[0])))[2:]
        # get storage value
        val = int(line.split()[2])
        
        # iterate through all mask combination and store in list with '-1' instead of '0'
        #  to allow correct interpretation
        masks = []
        x_count = mask.count('X')
        for x_comb in itertools.product(['-1','1'],repeat=x_count):
            mask_new = mask[:]
            for rep in x_comb:
                mask_new[mask_new.index('X')] = rep
            masks.append(mask_new)

        # iterate through each mask
        for out_list in masks:
            # reverse the mask list and iterate through
            for i,e in enumerate(out_list[::-1]):
                if i < len(loc) and e =='0':
                    out_list[-1-i] = loc[-1-i]
                elif i < len(loc) and e =='1':
                    out_list[-1-i] = '1'
                elif e =='-1':
                    out_list[-1-i] = '0'

            # join back the output list to binary and convert to decimal
            out_loc = int(''.join(out_list),2)

            # store in out dict
            out[out_loc] = val

sum(out.values())

3278997609887

## Day 15

In [840]:
d15 = aocd.get_data(day=15,year=2020)

In [898]:
start_list = {int(e):i for i,e in enumerate(d15.split(','))}
last_num = int(d15.split(',')[-1])

for i in range(len(start_list),30000000):
    old_index = start_list.get(last_num,(i - 1))
    cur_num = (i - 1) - old_index
    start_list[last_num] = (i-1)
    last_num = cur_num
print(cur_num)

1801753


## Day 16

In [899]:
d16 = aocd.get_data(day=16,year=2020)

In [928]:
rules = d16.split('\n')[:20]
my_ticket = [int(x) for x in d16.split('\n')[22].split(',')]
ticket_values = [int(y) for x in d16.split('\n')[25:] for y in x.split(',') ]

# my_ticket = [int(val) for val in x[1].split('\n')[1].split(',')]
NUM_FIELDS = len(my_ticket)
other_tickets = np.array([int(val) for val in re.findall('\d+', x[2])]).reshape(-1, NUM_FIELDS)
valid_ranges = np.array([int(val) for val in re.findall('\d+', x[0])]).reshape(NUM_FIELDS, 2, 2)
check_valid = np.zeros(other_tickets.shape)


In [954]:
rule_nums = [int(y) for x in rules for y in x.replace(' or ','-').split(': ')[1].split('-')]

In [960]:
rule_set = set()
for i,e in enumerate(rule_nums[::2]):
    for x in range(e,rule_nums[i+1]+1):
        rule_set.add(x)

In [968]:
out = 0
for tv in ticket_values:
    if tv not in rule_set:
        # print(tv)
        out += tv
print(out)

29878


In [978]:
rule_name = [x.split(':')[0] for x in rules]
rule_min1 = [int(x.split(': ')[1].split('-')[0]) for x in rules]
rule_max1 = [int(x.split(': ')[1].replace(' or ','-').split('-')[1]) for x in rules]
rule_min2 = [int(x.split(': ')[1].replace(' or ','-').split('-')[2]) for x in rules]
rule_max2 = [int(x.split(': ')[1].replace(' or ','-').split('-')[3]) for x in rules]

rule_df = pd.DataFrame([rule_min1,rule_max1,rule_min2,rule_max2],columns=rule_name)

In [1002]:
tickets_df = pd.DataFrame([x.split(',') for x in d16.split('\n')[25:]])
tickets_df = tickets_df.astype('int32')

In [1016]:
tickets_df['valid'] = 1
for i in range(20):
    tickets_df['valid'] = tickets_df['valid'] * tickets_df[i].apply(lambda x: 1 if x in rule_set else 0)

In [1052]:
tickets_valid = tickets_df[tickets_df.valid==1]

In [1056]:
col_names = 
for r in range(20):
    cols = []
    for c in range(20):
        if (tickets_valid.iloc[:,c].between(rule_df.iloc[0,r], rule_df.iloc[1,r]) \
          | tickets_valid.iloc[:,c].between(rule_df.iloc[2,r], rule_df.iloc[3,r])).all():
          cols.append(c)
    print(r,cols)
    col_names.append((r,cols))
print(col_names)

0 [1, 3, 4, 8, 9, 12, 15]
1 [0, 1, 3, 4, 5, 8, 9, 12, 14, 15, 17]
2 [1, 3, 4, 5, 8, 9, 12, 15]
3 [0, 1, 3, 4, 5, 8, 9, 12, 14, 15]
4 [1, 3, 4, 5, 8, 9, 12, 14, 15]
5 [0, 1, 3, 4, 5, 8, 9, 10, 12, 14, 15, 17]
6 [0, 1, 3, 4, 5, 6, 8, 9, 10, 12, 14, 15, 16, 17, 19]
7 [1, 9]
8 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19]
9 [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19]
10 [1, 3, 4, 8, 9, 12]
11 [1, 9, 12]
12 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
13 [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 16, 17, 19]
14 [1]
15 [1, 3, 4, 9, 12]
16 [1, 3, 9, 12]
17 [0, 1, 3, 4, 5, 6, 8, 9, 10, 12, 14, 15, 17, 19]
18 [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 19]
19 [0, 1, 3, 4, 5, 6, 8, 9, 10, 12, 14, 15, 17]
[(0, [1, 3, 4, 8, 9, 12, 15]), (1, [0, 1, 3, 4, 5, 8, 9, 12, 14, 15, 17]), (2, [1, 3, 4, 5, 8, 9, 12, 15]), (3, [0, 1, 3, 4, 5, 8, 9, 12, 14, 15]), (4, [1, 3, 4, 5, 8, 9, 12, 14, 15]), (5, [0, 1, 3, 4, 5, 8, 9, 10, 1

In [1065]:
s = 1
for i in [15,17,5,0,14,10]:
    s *= my_ticket[i]
print(s)

855438643439


In [1064]:
rule_df

departure location  departure station  departure platform  departure track  \
0                  33                 48                  37               41   
1                 679                646                 601              863   
2                 691                671                 619              875   
3                 971                966                 950              973   

   departure date  departure time  arrival location  arrival station  \
0              37              26                30               30   
1             145             246               542               75   
2             168             257               556               89   
3             965             972               960              954   

   arrival platform  arrival track  class  duration  price  route  row  seat  \
0                48             41     40        33     47     29   45    34   
1               274            561    237       317    365    415  762   888   
2               299            567    243       336    381    435  784   914   
3               958            957    952       972    957    951  972   968   

   train  type  wagon  zone  
0     50    45     44    28  
1    502   802    458   721  
2    513   825    475   735  
3    960   961    963   972

In [1020]:
# my_ticket = [int(val) for val in x[1].split('\n')[1].split(',')]
NUM_FIELDS = len(my_ticket)
other_tickets = np.array([int(val) for val in re.findall('\d+', x[2])]).reshape(-1, NUM_FIELDS)
valid_ranges = np.array([int(val) for val in re.findall('\d+', x[0])]).reshape(NUM_FIELDS, 2, 2)
check_valid = np.zeros(other_tickets.shape)
for i in range(NUM_FIELDS):
    for lower, upper in np.array(valid_ranges).reshape(-1, 2):
        check_valid[:, i] += (lower <= other_tickets[:, i]) & (other_tickets[:, i] < upper)
valid_tickets = other_tickets[np.prod(check_valid, axis=1) != 0]
possible_mappings = np.zeros((NUM_FIELDS, NUM_FIELDS))
for ticket_column in range(NUM_FIELDS):
    for range_column in range(NUM_FIELDS):
        check = np.zeros(len(valid_tickets))
        for lower, upper in valid_ranges[range_column]:
            check += (lower <= valid_tickets[:, ticket_column]) & (valid_tickets[:, ticket_column] <= upper)
        if np.sum(check == 0) == 0:
            possible_mappings[ticket_column, range_column] += 1
final_mapping = {}
while np.sum(possible_mappings) > 0:
    for ticket_column in range(NUM_FIELDS):
        if np.sum(possible_mappings[ticket_column]) == 1:
            range_column = np.argmax(possible_mappings[ticket_column])
            final_mapping[ticket_column] = range_column
            possible_mappings[:, range_column] = 0
return np.prod([my_ticket[k] for k, v in final_mapping.items() if v < 6])

0        948
1        947
2        944
3        949
4        949
5        948
6        949
7        941
8        949
9        946
10       949
11       948
12       949
13       949
14       946
15       938
16       946
17       948
18       949
19       943
valid      1
dtype: int64

## Day 17

In [1066]:
d17 = aocd.get_data(day=17,year=2020)

In [1089]:
 base = np.array([list(row) for row in d17.replace('#','1').replace('.','0').split()]).astype(int)

In [1098]:
from scipy import ndimage

In [1203]:
from scipy import ndimage
d17 = aocd.get_data(day=17,year=2020)

base = np.array([list(row) for row in d17.replace('#','1').replace('.','0').split()]).astype(int)

dimensions = 4
cycles = 10

full_cube = np.pad(base.reshape((*[1]*(dimensions-len(base.shape))),*base.shape), [[cycles,cycles]] * dimensions, 'constant')

neighbors_full = np.ones([3] * dimensions)

for _ in range(cycles):
    n_sum = ndimage.convolve(full_cube,neighbors_full,mode='constant') - full_cube
    full_cube = (((n_sum == 2) & (full_cube == 1)) | (n_sum == 3)).astype(int)
print(np.sum(full_cube))


12228


## Day 18

In [1204]:
d18 = aocd.get_data(day=18, year=2020)

In [1208]:
equations = d18.split('\n')

In [1426]:
def eval_lr(eq):
    p = re.compile(r'\d+[^\d]+?\d+')
    while p.search(eq):
        sub = p.search(eq)[0]
        val = eval(sub)
        eq = eq.replace(sub, str(val), 1)
    return(eval(eq))


def eval_paren(eq):
    p = re.compile(r'(\([^\(\)]+\))')
    s = 0
    for eq in equations:
        while p.search(eq):
            sub = p.search(eq)[0]
            val = eval_lr(sub[1:-1])
            eq = eq.replace(sub,str(val))
            # print(eq)
        o = eval_lr(eq)
        # print(eq,'=',o)
        s += o
    print(s)

    

5783053349377


In [1380]:
p = re.compile(r'(\([^\(\)]+\))')
s = 0
for eq in equations:
    while p.search(eq):
        sub = p.search(eq)[0]
        val = np.prod([eval(f) for f in sub[1:-1].split("*")])
        eq = eq.replace(sub,str(val))
    s += np.prod([eval(f) for f in eq.split("*")])
print(s)

74821486966872


## Day 19

In [1427]:
d19 = aocd.get_data(day=19,year=2020)

In [1629]:
tree = {x.split(': ')[0] : y.split('|') for x in d19.replace('"','').split('\n\n')[0].split('\n') for y in x.split(': ')[1:]}
for k,v in tree.items():
    tree[k] = [x.split() for x in v]

In [1621]:
test_vals = d19.split('\n\n')[1].split()

In [1668]:
def valid_list(base):
    new_trunk = []
    for i,branch in enumerate(base):
        raw = []
        for j,lookup_val in enumerate(branch):
            raw.append(tree.get(lookup_val,lookup_val))
        for e in itertools.product(*raw):
            new_trunk.append(list(itertools.chain(*e)))
    return(new_trunk)

def full_valid(id):
    start = tree[id]
    test = True
    while test == True:
        new = valid_list(start)
        if start == new:
            test = False
        else:
            start = new

    valid_set = [''.join(x) for x in new]
    return(valid_set)


In [1682]:
valid_set_42 = full_valid('42')
valid_set_31 = full_valid('31')

In [1698]:
part_a = 0
part_b = 0
for s in test_vals:
    s_rule = ''
    for i in range(int(len(s) / 8)):
        sub = s[i*8:(i+1)*8] 
        if sub in valid_set_42:
            s_rule += '1'
        elif sub in valid_set_31:
            s_rule += '0'
    ones = s_rule.count('1')
    zeros = s_rule.count('0')
    
    if ones > zeros and s_rule[:ones] == '1'* ones and s_rule[-zeros:] == '0'*zeros:
        part_b += 1
    if s_rule == '110':
        part_a += 1


print(part_a,part_b)        

272 374


## Day 20

In [1699]:
d20 = aocd.get_data(day=20,year=2020)

In [2042]:
N = 0; E = 1; S = 2; W = 3
tmap = dict()       # map from (N,E,S,W) edge numbers to tile IDs
tile_imgs = dict()  # map from (N,E,S,W) edge numbers to tiles

# Sea monster as array of zeroes and ones
sm = """00000000000000000010 
        10000110000110000111
        01001001001001001000"""
sm = np.array([list(l.strip()) for l in sm.split("\n")]).astype(np.int)

# Process input
with open("../../original_solutions/day_20/input_20.txt") as input_file:
    t_tiles = [tile.split("\n") for tile in input_file.read().split("\n\n")]
    tile_len = len(t_tiles[0][1].strip())
    for t_tile in t_tiles:
        tileID = int(re.match(r"Tile (\d+):", t_tile[0]).group(1))
        og_tile = np.array([list(line) for line in t_tile[1:]])
        og_tile[og_tile == "#"] = 1
        og_tile[og_tile == "."] = 0
        og_tile = og_tile.astype(np.int)

        # Perform all transformations on card, adding to dictionaries
        for i in range(2 * 2):
            tile = og_tile.copy()
            # Horizontal flip
            if i & 1 == 0:
                tile = np.flipud(tile)
            # Vertical flip
            if i & 2 == 0:
                tile = np.fliplr(tile)
            # Rotations
            for j in range(4):
                edges = (
                    int("".join(tile[0].astype(str)), 2),
                    int("".join(tile[:,-1].astype(str)), 2),
                    int("".join(tile[-1].astype(str)), 2),
                    int("".join(tile[:,0].astype(str)), 2)
                )
                tile_imgs[edges] = tile
                tmap[edges] = tileID
                tile = np.rot90(tile, -1)
    
# Count number of tile transformations that have each edge
occurences = defaultdict(int)
for tileT, tileID in tmap.items():
    for edge in tileT:
        occurences[edge] += 1
# find edge numbers that are on the boundary
bound_edges = set()
for edge, n in occurences.items():
    if n == 4: # must be 4 different transformations of the same tile
        bound_edges.add(edge)

# grid of tile transforms
g_len = int(math.sqrt(len(t_tiles)))

# find the corners
corners = []
for tileT, tileID in tmap.items():
    edges = [edge for edge in tileT if edge in bound_edges]
    if len(edges) == 2:
        corners.append((tileT, tileID))
        if len(edges) >= 3: print(tileT, tileID)
print(" -> part A:", math.prod(list(set([i for _, i in corners]))))

# Find the top-left corner candidates
tl_corners = []
for tileT, tileID in corners:
    if tileT[N] in bound_edges and tileT[W] in bound_edges:
        tl_corners.append((tileT, tileID))

# Place the rest of the tiles, starting with top-left corner, for each possible top-left corner
# This will generate all possible transformations of the image!
for tl_corner in tl_corners:
    grid = [[None for _ in range(g_len)] for _ in range(g_len)]
    grid[0][0] = tl_corner
    tmap_copy = deepcopy(tmap)
    # Remove top-left corner from map
    for tileT, tileID in list(tmap_copy.items()):
        if tileID == tl_corner[1]:
            tmap_copy.pop(tileT)
    # Place the tiles
    for row in range(g_len):
        for col in range(g_len):
            if grid[row][col] != None:
                continue
            match = None
            for tileT, tileID in tmap_copy.items():
                # check if neighbor's edges match this tile's edges
                for d, p in enumerate([(row - 1, col), (row, col + 1), (row + 1, col), (row, col - 1)]):
                    # check neighbor for matching edge num
                    if 0 <= p[0] < g_len and 0 <= p[1] < g_len:
                        neighbor = grid[p[0]][p[1]]
                        # empty neighbor should not be boundary
                        if neighbor == None:
                            continue
                        # check that opposite edge of neighbor tile matches edge of current tile
                        elif neighbor[0][(d + 2) % 4] != tileT[d]:
                            break
                    # ensure that if tile is on edge, edge sides are in boundary edges set
                    elif tileT[d] not in bound_edges:
                        break
                else:
                    match = (tileT, tileID)
                    break
            # remove all the transforms for the found tile from the map
            for tileT, tileID in list(tmap_copy.items()):
                if tileID == match[1]:
                    tmap_copy.pop(tileT)
            # set grid
            grid[row][col] = match

    # Place the tiles
    img_len = g_len * (tile_len - 2)
    img = np.ndarray((img_len, img_len), dtype=np.int)
    for row in range(g_len):
        for col in range(g_len):
            # Place the transformed tile into the image without the borders
            img[row * (tile_len - 2):(row + 1) * (tile_len - 2),
                col * (tile_len - 2):(col + 1) * (tile_len - 2)] =\
                tile_imgs[grid[row][col][0]][1:-1,1:-1]

    # find sea monsters
    sm_count = 0
    for row in range(img_len - sm.shape[0]):
        for col in range(img_len - sm.shape[1]):
            if np.all(img[row:row+sm.shape[0], col:col+sm.shape[1]] & sm == sm):
                sm_count += 1
    if sm_count > 0:
        print(" -> part B:", np.sum(img) - (sm_count * np.sum(sm)))
        break

1

In [2032]:
# import math

P = {int(p[5:9]): p[11:] for p in d20.split('\n\n')}
edge = lambda p,i: [p[:10], p[9::11], p[-10:], p[0::11]][i]
def transform(p):
    for _ in range(4):
        yield p
        yield '\n'.join(l[::-1] for l in p.split('\n')) # flip
        p = '\n'.join(''.join(l[::-1]) for l in zip(*p.split('\n'))) # rotate

def get_match(pieces, p, side):
    for o in pieces:
        if o in transform(p):
            continue
        for ot in transform(o):
            if edge(ot, (side+2)%4) == edge(p, side):
                return ot
    return 0

Z = P.values()
corners = [k for k,v in P.items() if sum(not get_match(Z, v, i) for i in range(4)) == 2]
print('Part 1:', math.prod(corners))

def get_line(pieces, p, orient):
    R = [p]
    for _ in range(11):
        R += [get_match(pieces, R[-1], orient)]
    return R

corner_tile = next(p for p in transform(P[corners[0]]) if (get_match(Z, p, 2) and get_match(Z, p, 3)))
G = [get_line(Z, a, 3) for a in get_line(Z, corner_tile, 2)]

image = '\n'.join(''.join(a[i+1:i+9] for a in B[::-1]) for B in G for i in range(11, 99, 11))

# import regex as re # Need `overlapped` option

spacing = '[.#\n]{77}'
monster = f'#.{spacing+"#....#"*3}##{spacing}.#{"..#"*5}'

for image_t in transform(image):
    m = len(re.findall(monster, image_t, overlapped=True))
    if m:
        print('Part 2:', sum(c == '#' for c in image_t) - 15*m)
        break

Part 1: 51214443014783
Part 2: 2065


In [2034]:
image.split()

['..#....#.#..........##...........####..#.#.##........#..#.#..#.#...#....#...#.....#....#...#..#.',
 '........#.#.....###...##......#.........###.#.#....#####..#.#......#.#.##...##....#.............',
 '...#...##.#...#............#.#..#..........###..#.#...#.#...##......#............#.#.#.#....#...',
 '..#.............##.....#.#........#.#......#.........#..##...#....#..#...#.#.#.#..#....#.......#',
 '...#......#....#.#.......#..#....#........##..#....#..#..........#...#...#........#.#.#.........',
 '..#....#.##.......#...#..#.....##.##...###..#.....##.##.#.....#.#.#..#....#.#..#................',
 '..#.....#...##.............#..#........#.#.#.##.#.##.......#..........#....#.#...##.#.#....##.#.',
 '..##.##.#...#....##...#......#.....#...#....#...#...............##..#......#....#..#...#..#...#.',
 '...#.#.###.............#.#.....###....#.........#.#..##..#........#..#......#..#.....#..#....#..',
 '..####..#.#....#...#....#.###...#.......#.#.....##.#....#..###.#.##...#.#..#...#......#..

In [2009]:
d20s = d20.replace('.','0').replace('#','1').split()
tiles = {}
edges = collections.defaultdict(set)
# edge_side = ['tn','ti','rn','ri','bn','bi','ln','li']
for i in range(144):
    top = i*12+2
    bottom = i*12+12
    tile_num = int(d20s[i*12+1].split(':')[0])
    tile = np.array([list(x) for x in d20s[top:bottom]]).astype(int)
    # print(d20s[bottom],bottom)
    edge_list = [int(d20s[top],2)
                ,int(d20s[top][::-1],2)
                ,int(''.join([x[9] for x in d20s[top:bottom]]),2)
                ,int(''.join([x[9] for x in d20s[top:bottom][::-1]]),2)
                ,int(d20s[bottom-1],2)
                ,int(d20s[bottom-1][::-1],2)
                ,int(''.join([x[0] for x in d20s[top:bottom]]),2)
                ,int(''.join([x[0] for x in d20s[top:bottom][::-1]]),2)]
    
    for j,e in enumerate(edge_list):
        edges[e].add(tile_num)

    tiles[tile_num] = tile

In [2014]:
# edges_unique = collections.defaultdict()
pairs = set(tuple(v) for v in edges.values() if len(v) == 2)

In [2019]:
match_tiles = [v for v in pairs if 1759 in v]

In [2026]:
a = set(match_tiles[0])
a.discard(1759)
print(a)

{2287}


In [ ]:
tile 
unmatched edge
    find match tile with unmatched edges and save for next st

cur_tile = np.flipud(tiles[1759])
full_grid = np.zeros([120,120])
for i in range(6):
    for j in range(6):
        full_grid


In [2008]:
print(np.flipud(tiles[1759]))
print(tiles[1759])

[[0 0 1 1 1 0 0 0 1 1]
 [1 0 0 1 1 0 1 0 0 1]
 [1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 1 0 0]]
[[1 0 1 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0]
 [0 1 0 1 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 1 0 1 0 0 1]
 [0 0 1 1 1 0 0 0 1 1]]


In [2004]:
print(tiles[2287])
print(np.rot90(tiles[2003],-1))
print(np.rot90(tiles[1759].transpose(),1))
print(np.rot90(tiles[1069],2))
# ,tiles[2287])
# print(tiles[1759].transpose())
# print(np.rot90(tiles[1759],-1))
# ?np.rot90


[[1 1 1 1 0 1 0 0 1 0]
 [1 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0]
 [1 1 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 1 0]
 [1 0 0 0 1 1 0 0 0 0]
 [0 1 0 1 1 1 1 0 0 0]]
[[0 1 0 1 1 1 1 0 0 0]
 [0 0 0 1 0 0 1 0 0 1]
 [1 0 0 0 0 1 1 1 1 1]
 [1 0 0 0 1 1 0 0 0 1]
 [1 0 0 0 1 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0 0 1 1]
 [1 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 1 0 0]]
[[0 0 1 1 1 0 0 0 1 1]
 [1 0 0 1 1 0 1 0 0 1]
 [1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 1 0 0]]
[[1 0 1 0 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 1]
 [1 0 0 1 0 0 1 1 0 1]
 [0 0 0 0 1 0 0 1 0 1]
 [1 0 0 1 0 1 1 0 1 0]
 [0 0 0 0 0 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 1 0 0 1]
 [1 1 1 0 0 0 1 1 1 1]]


In [1971]:
matched_edges = collections.defaultdict(int)
for k,v in edges.items():
    if len(v) >= 2:
        for i in v:
            matched_edges[i[0]] += 1

# sorted(matched_edges)
print(sorted(matched_edges.items(), key = 
             lambda kv:(kv[1], kv[0])))     



[(1759, 4), (2719, 4), (2801, 4), (3823, 4), (1031, 6), (1063, 6), (1069, 6), (1087, 6), (1249, 6), (1303, 6), (1307, 6), (1319, 6), (1471, 6), (1609, 6), (1699, 6), (1721, 6), (1723, 6), (1867, 6), (1871, 6), (1889, 6), (1949, 6), (2011, 6), (2203, 6), (2273, 6), (2287, 6), (2381, 6), (2411, 6), (2609, 6), (2663, 6), (2713, 6), (2917, 6), (2939, 6), (3037, 6), (3169, 6), (3259, 6), (3271, 6), (3529, 6), (3593, 6), (3607, 6), (3637, 6), (3697, 6), (3727, 6), (3769, 6), (3881, 6), (1019, 8), (1051, 8), (1061, 8), (1093, 8), (1109, 8), (1153, 8), (1163, 8), (1187, 8), (1279, 8), (1283, 8), (1301, 8), (1367, 8), (1409, 8), (1423, 8), (1427, 8), (1447, 8), (1459, 8), (1481, 8), (1523, 8), (1531, 8), (1549, 8), (1553, 8), (1559, 8), (1583, 8), (1607, 8), (1657, 8), (1667, 8), (1697, 8), (1747, 8), (1783, 8), (1787, 8), (1801, 8), (1811, 8), (1823, 8), (1831, 8), (1847, 8), (1861, 8), (1901, 8), (1907, 8), (1913, 8), (1933, 8), (1973, 8), (1979, 8), (2003, 8), (2063, 8), (2081, 8), (2089, 8)

In [1978]:
# grid = np.zeros([120,120])
grid[:10,:10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [1979]:
tiles[1759]

array([[1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 0, 0, 0, 1, 1]])

In [1852]:
1759 * 2719 * 2801 * 3823

51214443014783

## Day 21

In [1722]:
d21 = aocd.get_data(day=21, year=2020)

In [1758]:
ingredients = []
alergens = []
for food in d21.split('\n'):
    ingredients.append(food.split('(')[0].split())
    alergens.append(food.split('contains ')[1][:-1].split(', '))



In [1759]:
# ingredients
alergen_dict = {}
for i,e in enumerate(alergens):
    for a in e:
        ingredient_set = alergen_dict.get(a)
        if ingredient_set:
            alergen_dict[a] = set(ingredients[i]).intersection(ingredient_set)
        else:
            alergen_dict[a] = set(ingredients[i])


In [1760]:
alergen_dict

{'fish': {'dgsdtj', 'sjcvsr'},
 'peanuts': {'sjcvsr'},
 'soy': {'hn', 'vkdxfj'},
 'eggs': {'bstzgn', 'hn', 'kpksf'},
 'nuts': {'bstzgn', 'dgsdtj', 'kpksf', 'sjcvsr'},
 'sesame': {'bstzgn', 'dgsdtj', 'kmmqmv', 'sjcvsr'},
 'shellfish': {'kmmqmv', 'sjcvsr'},
 'wheat': {'bsfqgb', 'hn'}}

In [1752]:
possible_alergens = alergen_dict[' fish']
for v in alergen_dict.values():
    # print(v)
    possible_alergens =possible_alergens.union(v)

In [1770]:
[alergen_dict[v] for v in sorted(alergen_dict)]

[{'bstzgn', 'hn', 'kpksf'},
 {'dgsdtj', 'sjcvsr'},
 {'bstzgn', 'dgsdtj', 'kpksf', 'sjcvsr'},
 {'sjcvsr'},
 {'bstzgn', 'dgsdtj', 'kmmqmv', 'sjcvsr'},
 {'kmmqmv', 'sjcvsr'},
 {'hn', 'vkdxfj'},
 {'bsfqgb', 'hn'}]

In [1757]:
cnt = 0
for f in ingredients:
    for i in f:
        if i not in possible_alergens:
            cnt += 1
print(cnt)

2627


In [ ]:
 ' eggs': hn,
 ' fish': dgsdtj,
 ' nuts': kpksf,
 ' peanuts': sjcvsr,
 ' sesame': bstzgn,
 ' shellfish': kmmqmv,
 ' soy': vkdxfj,
 ' wheat': bsfqgb

  hn,dgsdtj,kpksf,sjcvsr,bstzgn,kmmqmv,vkdxfj,bsfqgb

## Day 22

In [1869]:
d22 = aocd.get_data(day=22, year=2020)

In [1925]:
p1 = collections.deque([int(x) for x in d22.split()[2:27]])
p2 = collections.deque([int(x) for x in d22.split()[29:]])
# len(d22.split())

In [1881]:
while len(p1) > 0 and len(p2) > 0:
    c1 = p1.popleft()
    c2 = p2.popleft()
    if c1 > c2:
        p1.append(c1)
        p1.append(c2)
    elif c2 > c1:
        p2.append(c2)
        p2.append(c1)

s = 0
for i,e in enumerate(p1):
    s += (50-i) * e
print(s)

In [1884]:
s = 0
for i,e in enumerate(p1):
    s += (50-i) * e
print(s)

31754


In [1968]:
def game(d1,d2):
    p1g = d1.copy()
    p2g = d2.copy()
    r = 0
    configs = []
    while len(p1g) > 0 and len(p2g) > 0:
        if [p1g,p2g] in configs:
            return([p1g,1])

        configs.append([p1g.copy(),p2g.copy()])

        c1 = p1g.popleft()
        c2 = p2g.popleft()
        if c1 <= len(p1g) and c2 <= len(p2g):
            # print('subgame')
            p1s = collections.deque(list(p1g)[:c1])
            p2s = collections.deque(list(p2g)[:c2])
            outcome = game(p1s,p2s)[1]
            # print('end with:',outcome)
            if outcome == 1:
                p1g.append(c1)
                p1g.append(c2)
            else:
                p2g.append(c2)
                p2g.append(c1)
        elif c1 > c2:
            p1g.append(c1)
            p1g.append(c2)
        elif c2 > c1:
            p2g.append(c2)
            p2g.append(c1)
        r+=1
        # print('round:',r, 'p1:', p1g)
    if len(p1g) == 0:
        return([p2g,2])
    else:
        return([p1g,1])


In [1969]:
winner = game(p1,p2)[0]

In [1970]:
s = 0
for i,e in enumerate(winner):
    s += (50-i) * e
print(s)

35436


## Day 23

In [2]:
d23 = aocd.get_data(day=23, year=2020)

In [3]:
d23

'589174263'

In [82]:
import time

In [180]:
def game23(start_dict,val,mod=9):

    cur_ptr = start_dict.get(val)
    sub_dict = {}
    next_ptr = cur_ptr
    for i in range (3):
        # print(i,next_ptr)
        sub_dict[next_ptr] = start_dict.pop(next_ptr)
        last_val = next_ptr
        next_ptr = sub_dict.get(next_ptr)
    
    i = 1
    dest_end = None
    while dest_end is None:
        dest_start = (val - i) % (mod + 1)
        dest_end = start_dict.get(dest_start)
        i+=1

    sub_dict[last_val] = dest_end

    start_dict[dest_start] = cur_ptr
    start_dict[val] = next_ptr
    
    start_dict.update(sub_dict)    

    return(start_dict,next_ptr)

In [179]:
start  = [int(x) for x in list('589174263')]
start_dict = dict(x for x in zip(start,start[1:]+start[:1]))

n = 5
for _ in range(100):
    start_dict,n = game23(start_dict,n)

n = 1
out = ''
while start_dict[n] != 1:
    n = start_dict[n]
    out += str(n)
print(out)

43896725


In [178]:
start  = [int(x) for x in list('589174263')] + [x for x in range(10,1000001)]
start_dict = dict(x for x in zip(start,start[1:]+start[:1]))
n = 5
for _ in range(10000000):
    start_dict,n = game23(start_dict,n,1000000)
a = start_dict[1]
b = start_dict[a]
print (a, '*', b, '=', a*b)

137066 * 21241 = 2911418906


## Day 24

In [181]:
d24 = aocd.get_data(day=24,year=2020)

In [250]:
tiles = d24.split()

In [251]:
flips = []
for t in tiles:
    se = t.count('se')
    sw = t.count('sw')
    ne = t.count('ne')
    nw = t.count('nw')
    ee = t.count('e') - se - ne
    ww = t.count('w') - sw - nw
    e = ee - ww + 0.5 * (se + ne - sw - nw)
    n = (ne + nw - se - sw)
    flips.append(tuple([e,n]))
flip_count = collections.Counter(flips)

In [258]:
sum(x%2 for x in flip_count.values())

377

In [253]:
def flip_step(base_dict):
    out_dict = {}
    x_min = int(min([x[0] for x in base_dict.keys()]))
    x_max = int(max([x[0] for x in base_dict.keys()]))
    y_min = min([x[1] for x in base_dict.keys()])
    y_max = max([x[1] for x in base_dict.keys()])

    for x in range((x_min-1)*2, (x_max+2)*2):
        for y in range(y_min-1, y_max+2):
            n = base_dict.get((x/2-1,y),0) % 2
            n += base_dict.get((x/2-.5,y+1),0) % 2 
            n += base_dict.get((x/2+.5,y+1),0) % 2 
            n += base_dict.get((x/2+1,y),0) % 2 
            n += base_dict.get((x/2+.5,y-1),0)  % 2 
            n += base_dict.get((x/2-.5,y-1),0) % 2 

            c = base_dict.get((x/2,y),0) % 2 

            if c == 1 and (n == 0 or n > 2):
                out_dict[(x/2,y)] = 0

            elif c == 0 and n == 2:
                out_dict[(x/2,y)] = 1
            else:
                out_dict[(x/2,y)] = c
    return(out_dict)
            

In [254]:
start = flip_count
for _ in range(100):
    start = flip_step(start)

sum(start.values())

4231

## Day 25

In [259]:
d25 = aocd.get_data(day=25, year=2020)

In [300]:
sub = 7
val = 1
for _ in range (10000000):
    val = val * sub
    val = val % 20201227
    if val in [int(x) for x in d25.split()]:
        print(sub,_,val)

7 1063910 10212254
7 1388394 12577395


In [298]:
sub = 12577395
val = 1
for _ in range(1063911):
    val = val * sub
    val = val % 20201227

print(val)

290487
